export const BIBLE_BOOKS = [
  { code:"GEN",  name:"Genesis",         short:"Gen",   chapters:50,  testament:"OT" },
  { code:"EXO",  name:"Exodus",          short:"Exo",   chapters:40,  testament:"OT" },
  { code:"LEV",  name:"Leviticus",       short:"Lev",   chapters:27,  testament:"OT" },
  { code:"NUM",  name:"Numbers",         short:"Num",   chapters:36,  testament:"OT" },
  { code:"DEU",  name:"Deuteronomy",     short:"Deu",   chapters:34,  testament:"OT" },
  { code:"JOS",  name:"Joshua",          short:"Jos",   chapters:24,  testament:"OT" },
  { code:"JDG",  name:"Judges",          short:"Jdg",   chapters:21,  testament:"OT" },
  { code:"RUT",  name:"Ruth",            short:"Rut",   chapters:4,   testament:"OT" },
  { code:"1SA",  name:"1 Samuel",        short:"1Sa",   chapters:31,  testament:"OT" },
  { code:"2SA",  name:"2 Samuel",        short:"2Sa",   chapters:24,  testament:"OT" },
  { code:"1KI",  name:"1 Kings",         short:"1Ki",   chapters:22,  testament:"OT" },
  { code:"2KI",  name:"2 Kings",         short:"2Ki",   chapters:25,  testament:"OT" },
  { code:"1CH",  name:"1 Chronicles",    short:"1Ch",   chapters:29,  testament:"OT" },
  { code:"2CH",  name:"2 Chronicles",    short:"2Ch",   chapters:36,  testament:"OT" },
  { code:"EZR",  name:"Ezra",            short:"Ezr",   chapters:10,  testament:"OT" },
  { code:"NEH",  name:"Nehemiah",        short:"Neh",   chapters:13,  testament:"OT" },
  { code:"EST",  name:"Esther",          short:"Est",   chapters:10,  testament:"OT" },
  { code:"JOB",  name:"Job",             short:"Job",   chapters:42,  testament:"OT" },
  { code:"PSA",  name:"Psalms",          short:"Psa",   chapters:150, testament:"OT" },
  { code:"PRO",  name:"Proverbs",        short:"Pro",   chapters:31,  testament:"OT" },
  { code:"ECC",  name:"Ecclesiastes",    short:"Ecc",   chapters:12,  testament:"OT" },
  { code:"SNG",  name:"Song of Solomon", short:"Sng",   chapters:8,   testament:"OT" },
  { code:"ISA",  name:"Isaiah",          short:"Isa",   chapters:66,  testament:"OT" },
  { code:"JER",  name:"Jeremiah",        short:"Jer",   chapters:52,  testament:"OT" },
  { code:"LAM",  name:"Lamentations",    short:"Lam",   chapters:5,   testament:"OT" },
  { code:"EZK",  name:"Ezekiel",         short:"Ezk",   chapters:48,  testament:"OT" },
  { code:"DAN",  name:"Daniel",          short:"Dan",   chapters:12,  testament:"OT" },
  { code:"HOS",  name:"Hosea",           short:"Hos",   chapters:14,  testament:"OT" },
  { code:"JOL",  name:"Joel",            short:"Jol",   chapters:3,   testament:"OT" },
  { code:"AMO",  name:"Amos",            short:"Amo",   chapters:9,   testament:"OT" },
  { code:"OBA",  name:"Obadiah",         short:"Oba",   chapters:1,   testament:"OT" },
  { code:"JON",  name:"Jonah",           short:"Jon",   chapters:4,   testament:"OT" },
  { code:"MIC",  name:"Micah",           short:"Mic",   chapters:7,   testament:"OT" },
  { code:"NAM",  name:"Nahum",           short:"Nam",   chapters:3,   testament:"OT" },
  { code:"HAB",  name:"Habakkuk",        short:"Hab",   chapters:3,   testament:"OT" },
  { code:"ZEP",  name:"Zephaniah",       short:"Zep",   chapters:3,   testament:"OT" },
  { code:"HAG",  name:"Haggai",          short:"Hag",   chapters:2,   testament:"OT" },
  { code:"ZEC",  name:"Zechariah",       short:"Zec",   chapters:14,  testament:"OT" },
  { code:"MAL",  name:"Malachi",         short:"Mal",   chapters:4,   testament:"OT" },
  { code:"MAT",  name:"Matthew",         short:"Mat",   chapters:28,  testament:"NT" },
  { code:"MRK",  name:"Mark",            short:"Mrk",   chapters:16,  testament:"NT" },
  { code:"LUK",  name:"Luke",            short:"Luk",   chapters:24,  testament:"NT" },
  { code:"JHN",  name:"John",            short:"Jhn",   chapters:21,  testament:"NT" },
  { code:"ACT",  name:"Acts",            short:"Act",   chapters:28,  testament:"NT" },
  { code:"ROM",  name:"Romans",          short:"Rom",   chapters:16,  testament:"NT" },
  { code:"1CO",  name:"1 Corinthians",   short:"1Co",   chapters:16,  testament:"NT" },
  { code:"2CO",  name:"2 Corinthians",   short:"2Co",   chapters:13,  testament:"NT" },
  { code:"GAL",  name:"Galatians",       short:"Gal",   chapters:6,   testament:"NT" },
  { code:"EPH",  name:"Ephesians",       short:"Eph",   chapters:6,   testament:"NT" },
  { code:"PHP",  name:"Philippians",     short:"Php",   chapters:4,   testament:"NT" },
  { code:"COL",  name:"Colossians",      short:"Col",   chapters:4,   testament:"NT" },
  { code:"1TH",  name:"1 Thessalonians", short:"1Th",   chapters:5,   testament:"NT" },
  { code:"2TH",  name:"2 Thessalonians", short:"2Th",   chapters:3,   testament:"NT" },
  { code:"1TI",  name:"1 Timothy",       short:"1Ti",   chapters:6,   testament:"NT" },
  { code:"2TI",  name:"2 Timothy",       short:"2Ti",   chapters:4,   testament:"NT" },
  { code:"TIT",  name:"Titus",           short:"Tit",   chapters:3,   testament:"NT" },
  { code:"PHM",  name:"Philemon",        short:"Phm",   chapters:1,   testament:"NT" },
  { code:"HEB",  name:"Hebrews",         short:"Heb",   chapters:13,  testament:"NT" },
  { code:"JAS",  name:"James",           short:"Jas",   chapters:5,   testament:"NT" },
  { code:"1PE",  name:"1 Peter",         short:"1Pe",   chapters:5,   testament:"NT" },
  { code:"2PE",  name:"2 Peter",         short:"2Pe",   chapters:3,   testament:"NT" },
  { code:"1JN",  name:"1 John",          short:"1Jn",   chapters:5,   testament:"NT" },
  { code:"2JN",  name:"2 John",          short:"2Jn",   chapters:1,   testament:"NT" },
  { code:"3JN",  name:"3 John",          short:"3Jn",   chapters:1,   testament:"NT" },
  { code:"JUD",  name:"Jude",            short:"Jud",   chapters:1,   testament:"NT" },
  { code:"REV",  name:"Revelation",      short:"Rev",   chapters:22,  testament:"NT" },
];

export const OT_BOOKS = BIBLE_BOOKS.filter((b) => b.testament === "OT");
export const NT_BOOKS = BIBLE_BOOKS.filter((b) => b.testament === "NT");
